name: portal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  wallet_lib:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/wallet_lib/assets/images/
    - packages/wallet_lib/assets/icons/dapp/
    - packages/wallet_lib/assets/icons/token/
    - packages/wallet_lib/assets/scripts/dapp/
    - packages/wallet_lib/assets/config/
